repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: v5.11.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst|toml)$
  - repo: local
    hooks:
      - id: flakeheaven
        name: flakeheaven
        description: "`Flakeheaven` it's a Flake8 wrapper to make it cool."
        entry: flakeheaven
        args: [ lint ]
        language: python
        types: [ python ]
        require_serial: true
        additional_dependencies: [
          'flake8~=4.0.1',
          'flakeheaven~=1.0.1',
          'flake8-builtins~=1.5.3',
          'flake8-blind-except~=0.2.1',
          'flake8-logging-format~=0.6.0',
          'flake8-bugbear~=22.4.25',
          'flake8-annotations~=2.9.0',
          'flake8-docstrings~=1.6.0',
          'flake8-bandit~=3.0.0',
          'darglint~=1.8.1',
        ]
