version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.14"
  apt_packages:
    - tree
  jobs:
    post_create_environment:
      # Installing doesn't work; the wrong target is used even with 'virtualenvs.create false'. There is a GitHub issue
      # which may be a better solution in the future: https://github.com/python-poetry/poetry/issues/1937
      - curl -LsSf https://astral.sh/uv/install.sh | UV_VERSION=0.9.26 sh
      - $HOME/.local/bin/uv export --only=docs,manual-extras --no-hashes --output=requirements-from-poetry.txt
      - cat requirements.txt

    # pre_build:
    #   - python -m sphinx -b linkcheck docs/ _build/linkcheck  # Fails for valid GitHub links?

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - plotting
        - cli

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf

submodules:
  include: all
